### ISSUE TITLE
Installation instructions don't work - Target path exists but is not a directory

### ISSUE THREAD

**Issue by acjones8** [iphands/instruction-counts#2]
Hello! I attempted to follow the instructions to install this utility on Gentoo, but they fail on the 3rd step, where one runs `pip install -t requirements.txt`. It yields this error:

>ERROR: Target path exists but is not a directory, will not continue.

I'm not very experienced with working with pip or python virtual environments in general, so I'm not sure what this means exactly (I can tell that requirements.txt is a file and not a directory, but I'm assuming pip is supposed to be able to read the file an install the dependencies?). 

I'll attempt to figure this out later as I'm busy at the moment, but just thought I'd open an issue now, in case anyone else has run into this problem or can recognize immediately what the error is. If it helps, I'm currently using python 3.11. I'm using the fish shell, but even after deleting the directory and running the steps in bash, I got exactly the same result. I can provide any other information that might be useful, just let me know what's required.

**Comment by iphands** [comment]
Ahh sorry that should read `pip install -r requirements.txt`

-r not -t

**Comment by iphands** [comment]
Fixed the readme
